[package]
name = "submarine"
version = "0.1.0"
authors = ["Sean Smith <scsmithr@gmail.com>"]
edition = "2018"

[dependencies]
vm = { path = "vm" }
memory = { path = "memory" }
device = { path = "device" }
boot = { path = "boot" }
boot_gen = { path = "boot_gen" }

log = "0.4"
env_logger = "0.6"
