[package]
name = "vm"
version = "0.1.0"
authors = ["Sean Smith <scsmithr@gmail.com>"]
edition = "2018"

[dependencies]
memory = { path = "../memory" }
device = { path = "../device" }

kvm-bindings = "0.1"
kvm-ioctls = "0.1.0"
libc = "0.2"
log = "0.4"
